//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web.Configuration;

namespace Ammonia {
    
    
    public partial class Site1 {
        
        /// <summary>
        /// head control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        
        /// <summary>
        /// logInForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm logInForm;
        
        /// <summary>
        /// textLogin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textLogin;
        
        /// <summary>
        /// textPass control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textPass;
        
        /// <summary>
        /// btnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        
        /// <summary>
        /// ContentPlaceHolder1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;

        protected bool loggedIn = false;

        protected void loginSubmit( object sender, EventArgs e)
        {
            if (loggedIn)
            {
                textLogin.Visible = true;
                textPass.Visible = true;
                accInfo.Visible = false;
                accInfo.Text = "Login";
                loginLabel.Visible = true;
                passwordLabel.Visible = true;
                btnSubmit.Text = "Войти";
                loggedIn = false;
            }
            else
            {
                if (textLogin.Text == "login" && textPass.Text == "password")
                {
                    textLogin.Visible = false;
                    textPass.Visible = false;
                    accInfo.Visible = true;
                    accInfo.Text = "Login";
                    loginLabel.Visible = false;
                    passwordLabel.Visible = false;
                    btnSubmit.Text = "Выйти";
                    loggedIn = true;
                }
            }
        }

        protected global::System.Web.UI.WebControls.Label accInfo;
        protected global::System.Web.UI.WebControls.Label loginLabel;
        protected global::System.Web.UI.WebControls.Label passwordLabel;
    }
}
