<%@ Page Language="C#" MasterPageFile="Admin.Master" AutoEventWireup="true" CodeBehind="News.aspx.cs" Inherits="Ammonia.Admin.News" %>
<asp:Content ID="Content1" ContentPlaceHolderID="headPH" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolderA" runat="server">
    <asp:Panel runat="server" ID="AdmNewsPanel">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#DCDCDC" />
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                <asp:BoundField DataField="Text" HeaderText="Text" SortExpression="Text" />
                <asp:BoundField DataField="Picture" HeaderText="Picture" SortExpression="Picture" />
                <asp:BoundField DataField="State" HeaderText="State" SortExpression="State" />
                <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" DataFormatString="{0:dd/mm/yyyy hh/m/ss}" HtmlEncode="False" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
            <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#0000A9" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#000065" />
        </asp:GridView>
        <asp:TextBox ID="txtTitle" runat="server"></asp:TextBox>
        <asp:TextBox ID="txtText" runat="server" Rows="5" TextMode="MultiLine" Width="278px"></asp:TextBox>
        <asp:TextBox ID="txtPicture" runat="server" OnTextChanged="txtPicture_TextChanged" TextMode="Url" AutoPostBack="True"></asp:TextBox>
        <asp:Button runat="server" ID="addRow" Text="Добавть новость" OnClick="addRow_Click"/>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:AmmConnectionString %>" SelectCommand="SELECT * FROM [News]" UpdateCommand="UPDATE [News] Set [Title]=@Title, [Text]=@Text, [Picture]=@Picture, [State]=@State, [Date]=Convert(Datetime,@Date,104) Where [Id]=@Id
            " DeleteCommand="DELETE from [News] Where [Id]=@Id"></asp:SqlDataSource>
        
        <asp:Image ID="Image1" runat="server" Visible="False" />
        
        <asp:Timer ID="Timer1" runat="server" Enabled="False" Interval="5000" OnTick="Timer1_Tick">
        </asp:Timer>
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
                <asp:Label ID="Label1" runat="server" ForeColor="Red"></asp:Label>
            </ContentTemplate>
        </asp:UpdatePanel>
        
    </asp:Panel>
    </asp:Content>
